# Generated by Django 5.2.5 on 2025-08-16 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('concert', 'Concert'), ('sport', 'Sport'), ('education', 'Education'), ('discount', 'Discount'), ('special', 'Special Offer'), ('other', 'Other')], max_length=20)),
                ('type', models.CharField(choices=[('once', 'One-time'), ('recurring', 'Recurring'), ('discount', 'Discount')], default='once', max_length=20)),
                ('date', models.DateTimeField()),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('media', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
